name: 'Check PR'
description: 'Confirm that PR follows Semantic styling'
runs:
    using: "composite"
    steps:
        - name: Set PR Target Branch validity
          id: is-valid
          if: >
              startsWith(github.event.pull_request.base.ref, 'development')||
              startsWith(github.event.pull_request.base.ref, 'build/')
          run: |
              OUTPUT=true
              echo "::set-output name=isValid::$OUTPUT"
        - name: echo isValid
          run: |
              echo ${{ steps.is-valid.outputs.isValid }}
        - name: PR title is valid
          if: ${{steps.is-valid.outputs.isValid == 'true'}}
          run: |
              echo 'Pull request target branch is valid.'
              echo ${{ steps.is-valid.outputs.isValid }}
        - name: PR title is invalid
          if: ${{ steps.is-valid.outputs.isValid != 'true'}}
          run: |
              echo ${{ steps.is-valid.outputs.isValid }}
              echo 'Pull request target branch is not valid.'
              exit 1
        - name: Set PR branch validity
          id: is-semantic
          if: >
              startsWith(github.event.pull_request.head.ref, 'feat/')||
              startsWith(github.event.pull_request.head.ref, 'fix/') ||
              startsWith(github.event.pull_request.head.ref, 'perf/') ||
              startsWith(github.event.pull_request.head.ref, 'docs/') ||
              startsWith(github.event.pull_request.head.ref, 'test/') ||
              startsWith(github.event.pull_request.head.ref, 'refactor/') ||
              startsWith(github.event.pull_request.head.ref, 'style/') ||
              startsWith(github.event.pull_request.head.ref, 'build/') ||
              startsWith(github.event.pull_request.head.ref, 'ci/') ||
              startsWith(github.event.pull_request.head.ref, 'chore/') ||
              startsWith(github.event.pull_request.head.ref, 'revert/')
          run: |
              OUTPUT=true
              echo "::set-output name=isSemantic::$OUTPUT"
        - name: echo isSemantic
          run: |
              echo ${{ steps.is-semantic.outputs.isSemantic }}
        - name: Branch name is valid
          if: ${{steps.is-semantic.outputs.isSemantic == 'true'}}
          run: |
              echo 'Pull request branch name is valid.'
              echo ${{ steps.is-semantic.outputs.isSemantic }}
        - name: Branch name is invalid
          if: ${{ steps.is-semantic.outputs.isSemantic != 'true'}}
          run: |
              echo ${{ steps.is-semantic.outputs.isSemantic }}
              echo 'Pull request branch name is not valid.'
              exit 1
        - name: Set PR title validity
          id: is-semantic
          if: >
              startsWith(github.event.pull_request.title, 'feat:')||
              startsWith(github.event.pull_request.title, 'fix:') ||
              startsWith(github.event.pull_request.title, 'perf:') ||
              startsWith(github.event.pull_request.title, 'docs:') ||
              startsWith(github.event.pull_request.title, 'test:') ||
              startsWith(github.event.pull_request.title, 'refactor:') ||
              startsWith(github.event.pull_request.title, 'style:') ||
              startsWith(github.event.pull_request.title, 'build:') ||
              startsWith(github.event.pull_request.title, 'ci:') ||
              startsWith(github.event.pull_request.title, 'chore:') ||
              startsWith(github.event.pull_request.title, 'revert:')
          run: |
              OUTPUT=true
              echo "::set-output name=isSemantic::$OUTPUT"
        - name: echo isSemantic
          run: |
              echo ${{ steps.is-semantic.outputs.isSemantic }}
        - name: PR title is valid
          if: ${{steps.is-semantic.outputs.isSemantic == 'true'}}
          run: |
              echo 'Pull request title is valid.'
              echo ${{ steps.is-semantic.outputs.isSemantic }}
        - name: PR title is invalid
          if: ${{ steps.is-semantic.outputs.isSemantic != 'true'}}
          run: |
              echo ${{ steps.is-semantic.outputs.isSemantic }}
              echo 'Pull request title is not valid.'
              exit 1
